config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  root :to => 'starter#home'
  
  get 'sessions/new'

  get 'users/new'

  get 'catering_items/CateringMenu'

  resources :cater_order_options

  get 'home/toppage'
  
  get 'cater_order_options/index'

  
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  resources :products do
    get :who_bought, on: :member
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
  <head>
    <title>Sharkos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  <link rel="apple-touch-icon" sizes="57x57" href="/images/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/images/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/images/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/images/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/images/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/images/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/images/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/images/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/images/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/images/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
  </head>

<body>
  <header> 
    <nav class="navbar-default">   <!--Nav bar default -->
      <div class = "navbar-header">

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      </div>

         <!-- Sharko Logo -- Aim for middle screen of nav -->
      <div class="navbar-brand">
        <%= link_to image_tag("sharkologosmall.png"), root_path, :alt => "Sharko BBQ Logo", :class =>"img-responsive" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  <!--Nav bar collapsed upong screensize -->
        <ul class="nav navbar-nav navbar-left"> <!-- Top NAV start -->
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
          <li class="<%= 'active' if current_page?(catering_items_CateringMenu_path) %>"><%= link_to "Catering Menu", catering_items_CateringMenu_path %></li>
        </ul>
        <!-- Right side TOP NAV page links -->
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(home_toppage_path) %>"><%= link_to "Admin", home_toppage_path %></li>
        <!--  if logged in, log out button appears, if logged out, login button appears -->  
          <% if logged_in? %>
          <!--No need to logout 'active' option, never is not a page the user visits, button only shows when user logins -->
            <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
          <% else %>
            <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <footer> <!--Footer NAV start -->
    <div class="navbar-inverse navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-collapse collapse" id="footer-body">
                <ul class="nav navbar-nav">
                  <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
                  <li class="<%= 'active' if current_page?(catering_items_CateringMenu_path) %>"><%= link_to "Catering Menu", catering_items_CateringMenu_path %></li>
                  <li class="<%= 'active' if current_page?(home_toppage_path) %>"><%= link_to "Admin", home_toppage_path %></li>
                </ul>
                <!--Social Media Links -->
                <ul id = "socialIcons" class="nav navbar-nav" >                  
                  <li><a class="btn-facebook btn-lg" href="https://www.facebook.com/Sharkos-Bbq-187615348055786/" target="blank_"><span class="fa fa-facebook"></span></a></li>
                  <li><a class="btn-twitter btn-lg" href="https://twitter.com/sharkosbbq?lang=en8" target="blank"><span class="fa fa-twitter"></span></a></li>
                </ul>
            </div>
          	<div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#footer-body">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
        </div>
    </div>
  </footer>

<%= yield %>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>